version: '3.3'
networks:
  caddy:
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/atm/containers/portainer/portainer-data:/data
    networks:
      - caddy
    ports:
      - 9000:9000

  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy
    ports:
      - 8033:8000

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - /home/atm/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/atm/containers/caddy/site:/srv
      - /home/atm/containers/caddy/caddy_data:/data
      - /home/atm/containers/caddy/caddy_config:/config
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443

volumes:
  caddy_data:
    external: true
  caddy_config:
  yacht:

